let profiles=[],currentIndex=0,currentProfile=null,currentAudio=null,phase="idle",runId=0,program=3,photoTimer=null;
const $=id=>document.getElementById(id),select=$("profileSelect"),jingle=$("jingleAudio"),dedication=$("dedicationAudio"),song=$("songAudio"),yearbookPhoto=$("yearbookPhoto"),currentPhoto=$("currentPhoto"),photoFallback=$("photoFallback");
const fields={name:$("classmateName"),song:$("songTitle"),artist:$("artistName"),year:$("songYear"),status:$("statusText"),elapsed:$("elapsedTime"),duration:$("durationTime"),progress:$("progressFill"),program:$("programNumber")};
boot();
async function boot(){try{const r=await fetch(`profiles.json?v=${Date.now()}`,{cache:"no-store"});profiles=await r.json();profiles.sort((a,b)=>a.name.localeCompare(b.name));const wanted=new URLSearchParams(location.search).get("id"),found=profiles.findIndex(p=>p.id===wanted);currentIndex=found>=0?found:0;profiles.forEach((p,i)=>select.add(new Option(`${p.name} — ${p.songTitle}`,i)));loadProfile(currentIndex)}catch(e){console.error(e);setStatus("Profile data unavailable")}}
function loadProfile(index){if(!profiles.length)return;stopAll(false);currentIndex=(index+profiles.length)%profiles.length;currentProfile=profiles[currentIndex];select.value=String(currentIndex);fields.name.textContent=currentProfile.name;fields.song.textContent=currentProfile.songTitle;fields.artist.textContent=currentProfile.artist;fields.year.textContent=currentProfile.year;$("activeNameLeft").textContent=currentProfile.name;$("previousName").textContent=profiles[(currentIndex-1+profiles.length)%profiles.length].name;$("nextName").textContent=profiles[(currentIndex+1)%profiles.length].name;$("artistStrip").textContent=currentProfile.artist;$("songStrip").textContent=currentProfile.songTitle;$("yearStrip").textContent=currentProfile.year;setPhotoSources();showPhoto("yearbook");dedication.src=currentProfile.dedicationFile;song.src=currentProfile.songFile;dedication.load();song.load();program=3;fields.program.textContent=program;setStatus("Ready");updateProgress();const u=new URL(location.href);u.searchParams.set("id",currentProfile.id);history.replaceState({},"",u)}
function setPhotoSources(){yearbookPhoto.style.display="";currentPhoto.style.display="";photoFallback.hidden=true;yearbookPhoto.onerror=()=>handlePhotoError(yearbookPhoto);currentPhoto.onerror=()=>handlePhotoError(currentPhoto);yearbookPhoto.src=currentProfile.yearbookPhoto||"";currentPhoto.src=currentProfile.currentPhoto||currentProfile.yearbookPhoto||"";yearbookPhoto.alt=`${currentProfile.name} yearbook photo`;currentPhoto.alt=`${currentProfile.name} current photo`;yearbookPhoto.style.objectPosition=currentProfile.yearbookPhotoPosition||"center 24%";currentPhoto.style.objectPosition=currentProfile.currentPhotoPosition||"center 24%"}
function handlePhotoError(img){img.style.display="none";if(yearbookPhoto.style.display==="none"&&currentPhoto.style.display==="none")photoFallback.hidden=false}
function showPhoto(which){clearTimeout(photoTimer);const current=which==="current";yearbookPhoto.classList.toggle("portrait-visible",!current);currentPhoto.classList.toggle("portrait-visible",current);$("showYearbook").classList.toggle("active",!current);$("showCurrent").classList.toggle("active",current)}
function scheduleCurrentPhoto(){clearTimeout(photoTimer);photoTimer=setTimeout(()=>showPhoto("current"),Math.min(6500,Math.max(2600,(dedication.duration||8)*520)))}
async function startSequence(){if(!currentProfile)return;stopAll(false);runId+=1;const token=runId;jingle.currentTime=0;dedication.currentTime=0;song.currentTime=0;showPhoto("yearbook");currentAudio=jingle;phase="jingle";setStatus("Reunion countdown jingle");try{await jingle.play()}catch{setStatus("Press Play again");return}jingle.onended=async()=>{if(token!==runId)return;currentAudio=dedication;phase="dedication";setStatus("Long-distance dedication");scheduleCurrentPhoto();try{await dedication.play()}catch{setStatus("Press Play to continue")}};dedication.onended=async()=>{if(token!==runId)return;showPhoto("current");phase="kachunk";setStatus("Changing selection");program=program===4?1:program+1;fields.program.textContent=program;await playKaChunk();if(token!==runId)return;currentAudio=song;phase="song";setStatus("Now playing");try{await song.play()}catch{setStatus("Press Play to continue")}}}
async function togglePlayPause(){if(!currentAudio||phase==="idle"||phase==="finished"){startSequence();return}if(currentAudio.paused){try{await currentAudio.play();setStatus(phase==="song"?"Now playing":phase==="dedication"?"Long-distance dedication":"Reunion countdown jingle")}catch{setStatus("Press Play again")}}else{currentAudio.pause();setStatus("Paused")}}
function pauseCurrent(){if(!currentAudio)return;currentAudio.pause();setStatus("Paused")}
function stopAll(show=true){runId+=1;clearTimeout(photoTimer);[jingle,dedication,song].forEach(a=>{a.pause();a.currentTime=0});currentAudio=null;phase="idle";updateProgress();if(show)setStatus("Stopped")}
function updateProgress(){if(!currentAudio){fields.elapsed.textContent="0:00";fields.duration.textContent="0:00";fields.progress.style.width="0%";return}const c=currentAudio.currentTime||0,d=currentAudio.duration||0;fields.elapsed.textContent=formatTime(c);fields.duration.textContent=formatTime(d);fields.progress.style.width=d?`${c/d*100}%`:"0%"}
function playKaChunk(){return new Promise(resolve=>{const AC=window.AudioContext||window.webkitAudioContext,ctx=new AC(),now=ctx.currentTime,g=ctx.createGain();g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.65,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+.42);g.connect(ctx.destination);const o=ctx.createOscillator();o.type="triangle";o.frequency.setValueAtTime(110,now);o.frequency.exponentialRampToValueAtTime(45,now+.2);o.connect(g);o.start(now);o.stop(now+.24);setTimeout(()=>{ctx.close();resolve()},480)})}
function setStatus(t){fields.status.textContent=String(t).toUpperCase()}function formatTime(s){const n=Math.max(0,Math.floor(Number.isFinite(s)?s:0));return `${Math.floor(n/60)}:${String(n%60).padStart(2,"0")}`}
select.addEventListener("change",e=>loadProfile(Number(e.target.value)));$("previousProfile").addEventListener("click",()=>loadProfile(currentIndex-1));$("nextProfile").addEventListener("click",()=>loadProfile(currentIndex+1));$("randomProfile").addEventListener("click",()=>{if(profiles.length<2)return;let i=currentIndex;while(i===currentIndex)i=Math.floor(Math.random()*profiles.length);loadProfile(i)});$("showYearbook").addEventListener("click",()=>showPhoto("yearbook"));$("showCurrent").addEventListener("click",()=>showPhoto("current"));$("playButton").addEventListener("click",togglePlayPause);$("pauseButton").addEventListener("click",pauseCurrent);$("restartButton").addEventListener("click",startSequence);$("stopButton").addEventListener("click",()=>stopAll(true));[jingle,dedication,song].forEach(a=>{a.addEventListener("timeupdate",updateProgress);a.addEventListener("loadedmetadata",updateProgress)});song.addEventListener("ended",()=>{phase="finished";currentAudio=null;setStatus("Finished");fields.progress.style.width="100%"});
